# Generated by Django 5.0.4 on 2024-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "PUBLIC"),
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("ADMIN", "Admin"),
                    ("SUPER_ADMIN", "Super admin"),
                    ("STUDIES_DIRECTION", "Studies direction"),
                    ("ALUMNI", "Alumni"),
                    ("PARTNER", "Partner"),
                ],
                max_length=63,
            ),
        ),
    ]
