# Generated by Django 5.0.4 on 2024-05-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorActivity',
            fields=[
                ('sectorId', models.AutoField(primary_key=True, serialize=False)),
                ('sectorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=255)),
                ('organizationDescription', models.TextField()),
                ('organizationAddress', models.TextField()),
                ('organizationEmail', models.EmailField(max_length=255)),
                ('organizationPhone', models.CharField(max_length=20)),
                ('organizationSize', models.IntegerField()),
                ('organizationCountry', models.CharField(max_length=50)),
                ('websiteLink', models.URLField()),
                ('organizationLogo', models.ImageField(upload_to='partnership/logos/')),
                ('officialDocument', models.FileField(upload_to='partnership/official_documents')),
                ('sectorActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partnership.sectoractivity')),
            ],
        ),
    ]
