# Generated by Django 5.0.4 on 2024-06-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorActivity',
            fields=[
                ('sectorId', models.AutoField(primary_key=True, serialize=False)),
                ('sectorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='partnership/logos/')),
                ('official_document', models.FileField(upload_to='partnership/official_documents')),
                ('is_validated', models.BooleanField(default=False)),
                ('sectorActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partnership.sectoractivity')),
            ],
        ),
    ]
