# Generated by Django 5.0.4 on 2024-06-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0003_diplome_is_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_range', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('level', models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=255)),
                ('rate', models.FloatField()),
                ('image', models.ImageField(upload_to='courses/')),
            ],
        ),
    ]
