# Generated by Django 5.0.4 on 2024-05-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/success_stories')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('story_date', models.DateField()),
            ],
        ),
    ]
