# Generated by Django 5.0.4 on 2024-04-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_link',
            field=models.URLField(blank=True),
        ),
    ]
