# Generated by Django 5.0.4 on 2024-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_slider_slider_image_alter_slider_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='school/slider/'),
        ),
    ]
