# Generated by Django 5.0.4 on 2024-06-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_news_image_alter_event_event_name_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_file',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school/events/images'),
        ),
    ]
