# Generated by Django 5.0.4 on 2024-04-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_slider_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='event',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='event',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='defense',
            name='event',
        ),
        migrations.RemoveField(
            model_name='defense',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='Defense',
        ),
        migrations.DeleteModel(
            name='Examiner',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
