# Generated by Django 5.0.4 on 2024-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_action_name',
            field=models.CharField(max_length=255),
        ),
    ]
