# Generated by Django 5.0.4 on 2024-04-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_slider_slider_action_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_action_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_description',
            field=models.CharField(max_length=255),
        ),
    ]
