# Generated by Django 5.0.4 on 2024-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_slider_slider_action_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('image_description', models.TextField()),
                ('link_image', models.ImageField(upload_to='school/gallery/')),
            ],
        ),
    ]
