# Generated by Django 5.0.4 on 2024-05-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_schoolgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolgallery',
            name='object_id',
        ),
    ]
