# Generated by Django 5.0.4 on 2024-05-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='clubs/logo/')),
                ('member_count', models.IntegerField()),
                ('event_count', models.IntegerField()),
                ('description', models.TextField()),
                ('opening_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubEventExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.event')),
            ],
        ),
    ]
