# Generated by Django 5.0.4 on 2024-06-11 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='clubs/logo/')),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100, null=True)),
                ('opening_date', models.DateField()),
                ('major_event', models.CharField(max_length=100, null=True)),
                ('member_count', models.IntegerField()),
                ('event_count', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('discord_link', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubEventExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.event')),
            ],
        ),
    ]
