# Generated by Django 5.0.4 on 2024-05-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
