# Generated by Django 5.0.4 on 2024-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='discord_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='website_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
    ]
